artifact_uri: file:c:/Users/dsy92/OneDrive/Desktop/Weapon-Detection/models/runs/mlflow/818077838994344116/0f5550c21d2642da86d9e0bd3dc350b2/artifacts
end_time: null
entry_point_name: ''
experiment_id: '818077838994344116'
lifecycle_stage: active
run_id: 0f5550c21d2642da86d9e0bd3dc350b2
run_name: weapon-detector-tl2
run_uuid: 0f5550c21d2642da86d9e0bd3dc350b2
source_name: ''
source_type: 4
source_version: ''
start_time: 1746076696280
status: 1
tags: []
user_id: dsy92
