artifact_uri: file:c:/Users/dsy92/OneDrive/Desktop/Weapon-Detection/models/runs/mlflow/818077838994344116/ff3ca4d6a71d4be18b254aa00b7b0ff1/artifacts
end_time: 1746116264606
entry_point_name: ''
experiment_id: '818077838994344116'
lifecycle_stage: active
run_id: ff3ca4d6a71d4be18b254aa00b7b0ff1
run_name: weapon-detector21
run_uuid: ff3ca4d6a71d4be18b254aa00b7b0ff1
source_name: ''
source_type: 4
source_version: ''
start_time: 1746116044123
status: 3
tags: []
user_id: dsy92
