artifact_uri: file:c:/Users/dsy92/OneDrive/Desktop/Weapon-Detection/models/runs/mlflow/818077838994344116/a68141cdeb4244dea02bd0f594e4553c/artifacts
end_time: null
entry_point_name: ''
experiment_id: '818077838994344116'
lifecycle_stage: active
run_id: a68141cdeb4244dea02bd0f594e4553c
run_name: weapon-detector22
run_uuid: a68141cdeb4244dea02bd0f594e4553c
source_name: ''
source_type: 4
source_version: ''
start_time: 1746116393534
status: 1
tags: []
user_id: dsy92
