artifact_location: file:c:/Users/dsy92/OneDrive/Desktop/Weapon-Detection/models/runs/mlflow/0
creation_time: 1746049356254
experiment_id: '0'
last_update_time: 1746049356254
lifecycle_stage: active
name: Default
